### ISSUE TITLE
version文件是怎么生成的呢？

### ISSUE THREAD

**Issue by dotlive** [CatImmortal/CatAsset#1]
version文件是怎么生成的呢？

**Comment by CatImmortal** [comment]
示例中的version文件是手写的，每次打包后都得手动改一下里面的版本号才能获取正确结果
需要请求version文件是为了确定最新版本的资源的PrefixUri，这个属于上层逻辑，具体实现根据项目需求决定
如果在资源服务器上没有版本区分的话那完全可以不请求version文件，直接进行资源清单检查
