### ISSUE TITLE
在Unity 2022.3.3 中，打包出现报告空引用

### ISSUE THREAD

**Issue by KTSAMA001** [CatImmortal/CatAsset#5]
NullReferenceException: Object reference not set to an instance of an object
BuildCacheUtility.SetCurrentBuildContent (UnityEditor.Build.Pipeline.Interfaces.IBuildContent content) (at ./Library/PackageCache/com.unity.scriptablebuildpipeline@1.21.5/Editor/Utilities/BuildCacheUtility.cs:42)
UnityEditor.Build.Pipeline.ContentPipeline.BuildAssetBundles (UnityEditor.Build.Pipeline.Interfaces.IBundleBuildParameters parameters, UnityEditor.Build.Pipeline.Interfaces.IBundleBuildContent content, UnityEditor.Build.Pipeline.Interfaces.IBundleBuildResults& result, System.Collections.Generic.IList`1[T] taskList, UnityEditor.Build.Pipeline.Interfaces.IContextObject[] contextObjects) (at ./Library/PackageCache/com.unity.scriptablebuildpipeline@1.21.5/Editor/ContentPipeline.cs:122)
CatAsset.Editor.BuildPipeline.BuildBundles (UnityEditor.BuildTarget targetPlatform, System.Boolean isBuildPatch) (at Assets/CatAsset/Editor/BuildPipeline/BuildPipeline.cs:88)
CatAsset.Editor.ConfigWindow.DrawButtons () (at Assets/CatAsset/Editor/Window/BundleBuildWindow/SubWindows/Config/ConfigWindow.cs:269)
CatAsset.Editor.ConfigWindow.DrawSubWindow (UnityEngine.Rect position) (at Assets/CatAsset/Editor/Window/BundleBuildWindow/SubWindows/Config/ConfigWindow.cs:50)
CatAsset.Editor.BundleBuildWindow.OnGUI () (at Assets/CatAsset/Editor/Window/BundleBuildWindow/BundleBuildWindow.cs:74)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition) (at <c6e522daeb5e447db61a1052f6be2b6d>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect dockAreaRect) (at <c6e522daeb5e447db61a1052f6be2b6d>:0)
UnityEditor.DockArea.OldOnGUI () (at <c6e522daeb5e447db61a1052f6be2b6d>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus, System.Boolean verifyBounds) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.IMGUIContainer.ProcessEvent (UnityEngine.UIElements.EventBase evt) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtCurrentTargetAndPhase (UnityEngine.UIElements.EventBase evt) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.UIElementsUtility.UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& eventHandled) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.UIEventRegistration.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.UIElements.UIEventRegistration+<>c.<.cctor>b__1_2 (System.Int32 i, System.IntPtr ptr) (at <73c7cf6473374eca8332474b6bd3c29a>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr, System.Boolean& result) (at <a09f044aced446deb8bdcfabea3f6e19>:0)

**Comment by Kakishizi** [comment]
请问这个问题最后怎么解决呀？是无法使用2022版本么

**Comment by KTSAMA001** [comment]
> 请问这个问题最后怎么解决呀？是无法使用2022版本么

暂时还不行
